<?php require VIEWS_PATH . 'includes/header.phtml'; ?>
<div class="container">

    <div class="jumbotron">
        <h1 class="display-4">Bem vindo ao projeto!</h1>
        <p class="lead">Projeto criado com sucesso.</p>
        <hr class="my-4">
        <p>Projeto criado usando PHP Orientado a Objetos. Catálogo de Produtos</p>
        <a class="btn btn-primary btn-lg" href="about" role="button">Saiba mais</a>
    </div>
    <div class="row">
        <?php foreach($this->products as $product): ?>
        <div class="col-md-4">
            <img src="http://via.placeholder.com/350x150?text=<?= $product['name']; ?>" alt="" class="img-responsive">
            <h2><a href="<?=HOME;?>/product/<?= $product['id']; ?>"><?= $product['name']; ?></a></h2>
            <p><?= $product['description']; ?></p>
            <p><?= number_format($product['price'], 2, ',', '.'); ?></p>
        </div>
        <?php endforeach; ?>
    </div>

</div>
<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>