<?php require VIEWS_PATH . 'includes/header.phtml'; ?>
    <div class="container">

        <div class="jumbotron">
            <h1 class="display-4">Sobre</h1>
        </div>
        <div class="col-md-12">
            <h2>A Instituição</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci amet beatae blanditiis cumque, debitis deserunt dicta earum ipsam iste maxime modi quam qui repudiandae tenetur, ullam. A reiciendis vitae voluptatibus!
            </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci amet beatae blanditiis cumque, debitis deserunt dicta earum ipsam iste maxime modi quam qui repudiandae tenetur, ullam. A reiciendis vitae voluptatibus!
            </p>
            <h2>Nossas Metas</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci amet beatae blanditiis cumque, debitis deserunt dicta earum ipsam iste maxime modi quam qui repudiandae tenetur, ullam. A reiciendis vitae voluptatibus!
            </p>
            <h2>Valores</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci amet beatae blanditiis cumque, debitis deserunt dicta earum ipsam iste maxime modi quam qui repudiandae tenetur, ullam. A reiciendis vitae voluptatibus!
            </p>
        </div>

    </div>
<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>