<?php require VIEWS_PATH . 'includes/header.phtml'; ?>
<div class="container">

    <div class="jumbotron">
        <h1 class="display-4">Bem vindo ao projeto!</h1>
        <p class="lead">Projeto criado com sucesso.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </div>

</div>
<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>